---
title: "Dosage Descriptive Statistics and Modelling"
format: html
editor: visual
---

```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(lmtp)
library(SuperLearner)
#library(parallel)
```

## Reading Data

```{r}
data_bup <- readRDS(here::here("data/processed/data_bup.rds"))
data_met <- readRDS(here::here("data/processed/data_met.rds"))
```

## Descriptive Stats Stratified by Race and Week

### bup dose in long format for summary statistics

```{r}
data_bup_long <- data_bup |>
    pivot_longer(
    cols = starts_with("wk"),
    names_to = c("week", "type_name"),
    names_pattern = "(wk[0-9]+).?(.*)",
    values_to = "count") |>
    pivot_wider(id_cols = c("who", "xrace", "week"),
                names_from = "type_name",
                values_from = "count") |>
    mutate(dose_this_week = case_when(
        censor == 0 ~ as.numeric(NA),
        TRUE ~ dose_this_week),
        week = as.integer(gsub("^.{0,2}", "", week))) |>
        group_by(week, xrace) |>
        summarize(avg = mean(dose_this_week, na.rm = TRUE),
                  sd = sd(dose_this_week, na.rm = TRUE),
                  se = plotrix::std.error(dose_this_week, na.rm = TRUE),
                  low = avg - 1.96*se,
                  high = avg + 1.96*se,
                  count = n(),
                  max = max(dose_this_week, na.rm = TRUE),
                  min = min(dose_this_week, na.rm = TRUE),
                  range_bup = max - min) |>
    mutate(xrace = case_when(xrace == "1" ~ "White",
                             xrace == "2" ~ "Black",
                             xrace == "3" ~ "Hispanic")) |>
    filter(week <= 4)
```

### met dose in long format for summary statistics

```{r}
data_met_long <- data_met |>
    pivot_longer(
    cols = starts_with("wk"),
    names_to = c("week", "type_name"),
    names_pattern = "(wk[0-9]+).?(.*)",
    values_to = "count") |>
    pivot_wider(id_cols = c("who", "xrace", "week"),
                names_from = "type_name",
                values_from = "count") |>
    mutate(dose_this_week = case_when(
        censor == 0 ~ as.numeric(NA),
        TRUE ~ dose_this_week),
        week = as.integer(gsub("^.{0,2}", "", week))) |>
    group_by(week, xrace) |>
        summarize(avg = mean(dose_this_week, na.rm = TRUE),
                  sd = sd(dose_this_week, na.rm = TRUE),
                  se = plotrix::std.error(dose_this_week, na.rm = TRUE),
                  low = avg - 1.96*se,
                  high = avg + 1.96*se,
                  count = n(),
                  max = max(dose_this_week, na.rm = TRUE),
                  min = min(dose_this_week, na.rm = TRUE),
                  range_bup = max - min) |>
    mutate(xrace = case_when(xrace == "1" ~ "White",
                             xrace == "2" ~ "Black",
                             xrace == "3" ~ "Hispanic")) |>
    filter(week <= 4)
```

## Saving Results

```{r}
saveRDS(data_bup_long, here::here("data/processed/data_bup_long.rds"))
saveRDS(data_met_long, here::here("data/processed/data_met_long.rds"))
```
