---
title: "Dosage Descriptive Statistics and Modelling"
format: html
editor: visual
---

```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggalluvial)
library(gtsummary)
library(patchwork)

knitr::opts_chunk$set(warning=FALSE, message=FALSE)
knitr::opts_chunk$set(fig.width=18, fig.height=12) 

source(here::here("scripts/source/utils_adapted.R"))
source(here::here("scripts/source/unadjusted_ci.R"))
```

## Reading/Storing Results

### Reading Results for Marginal CI

```{r}
data_bup_long <- readRDS(here::here("data/processed/data_bup_long.rds"))

data_met_long <- readRDS(here::here("data/processed/data_met_long.rds"))

data_bup_long_ungrouped <- readRDS(here::here("data/processed/data_bup_long_ungrouped.rds"))

data_met_long_ungrouped <- readRDS(here::here("data/processed/data_met_long_ungrouped.rds"))

met_results_all <- data.frame(week = integer(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

met_results_lim <- data.frame(week = integer(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

bup_results_all <- data.frame(week = integer(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

bup_results_lim <- data.frame(week = integer(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

# Loop through the file paths and read the RDS files into data frames
for (j in 1:3)
{
met_results_all_temp <- data.frame(week = numeric(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

met_results_lim_temp <- data.frame(week = numeric(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

bup_results_all_temp <- data.frame(week = numeric(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

bup_results_lim_temp <- data.frame(week = numeric(0), race = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

for (i in 1:4) {
  data_met <- readRDS(here::here(paste0("./data/102623/met/","result_met", j, sep = "_", i, ".rds")))
  met_results_all_temp[[i, "week"]] <- i
  met_results_all_temp[[i, "race"]] <- j
  met_results_all_temp[[i, "theta"]] <- data_met$theta
  met_results_all_temp[[i, "se"]] <- data_met$standard_error
  met_results_all_temp[[i, "lower"]] <- data_met$low
  met_results_all_temp[[i, "upper"]] <- data_met$high
  
  data_met_lim <- readRDS(here::here(paste0("./data/102623/met/","result_met_limited", j, sep = "_", i, ".rds")))
  met_results_lim_temp[[i, "week"]] <- i
  met_results_lim_temp[[i, "race"]] <- j
  met_results_lim_temp[[i, "theta"]] <- data_met_lim$theta
  met_results_lim_temp[[i, "se"]] <- data_met_lim$standard_error
  met_results_lim_temp[[i, "lower"]] <- data_met_lim$low
  met_results_lim_temp[[i, "upper"]] <- data_met_lim$high
 
  data_bup <- readRDS(here::here(paste0("./data/102623/bup/","result", j, sep = "_", i, ".rds")))
  bup_results_all_temp[[i, "week"]] <- i
  bup_results_all_temp[[i, "race"]] <- j
  bup_results_all_temp[[i, "theta"]] <- data_bup$theta
  bup_results_all_temp[[i, "se"]] <- data_bup$standard_error
  bup_results_all_temp[[i, "lower"]] <- data_bup$low
  bup_results_all_temp[[i, "upper"]] <- data_bup$high
  
  data_bup_lim <- readRDS(here::here(paste0("./data/102623/bup/","result_limited", j, sep = "_", i, ".rds")))
  bup_results_lim_temp[[i, "week"]] <- i
  bup_results_lim_temp[[i, "race"]] <- j
  bup_results_lim_temp[[i, "theta"]] <- data_bup_lim$theta
  bup_results_lim_temp[[i, "se"]] <- data_bup_lim$standard_error
  bup_results_lim_temp[[i, "lower"]] <- data_bup_lim$low
  bup_results_lim_temp[[i, "upper"]] <- data_bup_lim$high
}

met_results_all <- met_results_all |>
    merge(met_results_all_temp, all = TRUE)

met_results_lim <- met_results_lim |>
    merge(met_results_lim_temp, all = TRUE) 

bup_results_all <- bup_results_all |>
    merge(bup_results_all_temp, all = TRUE)

bup_results_lim <- bup_results_lim |>
    merge(bup_results_lim_temp, all = TRUE)
}

met_results_all <- met_results_all |>
    mutate(race = as.factor(race)) |>
    mutate(race = case_when(race == "1" ~ "White",
                             race == "2" ~ "Black",
                             race == "3" ~ "Hispanic"))

met_results_lim <- met_results_lim |>
    mutate(race = as.factor(race)) |>
    mutate(race = case_when(race == "1" ~ "White",
                             race == "2" ~ "Black",
                             race == "3" ~ "Hispanic"))

bup_results_all <- bup_results_all |>
    mutate(race = as.factor(race)) |>
    mutate(race = case_when(race == "1" ~ "White",
                             race == "2" ~ "Black",
                             race == "3" ~ "Hispanic"))

bup_results_lim <- bup_results_lim |>
    mutate(race = as.factor(race)) |>
    mutate(race = case_when(race == "1" ~ "White",
                             race == "2" ~ "Black",
                             race == "3" ~ "Hispanic"))
```

### Reading Results for Simultaneous CI

```{r}
# bup limited 
bup_as_1 <- list()
bup_as_2 <- list()
bup_as_3 <- list()
met_as_1 <- list()
met_as_2 <- list()
met_as_3 <- list()
bup_1 <- list()
bup_2 <- list()
bup_3 <- list()
met_1 <- list()
met_2 <- list()
met_3 <- list()

for (i in 1:4) {
    
    #bup limited
    bup_as_1[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result_limited", "1", sep = "_", i, ".rds")))
    
    bup_as_2[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result_limited", "2", sep = "_", i, ".rds")))
    
    bup_as_3[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result_limited", "3", sep = "_", i, ".rds")))
    
    #met limited
    met_as_1[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met_limited", "1", sep = "_", i, ".rds")))
    
    met_as_2[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met_limited", "2", sep = "_", i, ".rds")))

    met_as_3[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met_limited", "3", sep = "_", i, ".rds")))
    
    # bup all
    bup_1[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result", "1", sep = "_", i, ".rds")))

    bup_2[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result", "2", sep = "_", i, ".rds")))
    
    bup_3[[i]] <- readRDS(here::here(paste0("./data/102623/bup/","result", "3", sep = "_", i, ".rds")))

    # met all
    met_1[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met", "1", sep = "_", i, ".rds")))
    met_2[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met", "2", sep = "_", i, ".rds")))
    met_3[[i]] <- readRDS(here::here(paste0("./data/102623/met/","result_met", "3", sep = "_", i, ".rds")))
}

bup_all_12_df <- summarize_results(bup_1, bup_2, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
bup_all_23_df <- summarize_results(bup_2, bup_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
bup_all_13_df <- summarize_results(bup_1, bup_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)

met_all_12_df <- summarize_results(met_1, met_2, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
met_all_23_df <- summarize_results(met_2, met_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
met_all_13_df <- summarize_results(met_1, met_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)

bup_as_12_df <- summarize_results(bup_as_1, bup_as_2, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
bup_as_23_df <- summarize_results(bup_as_2, bup_as_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
bup_as_13_df <- summarize_results(bup_as_1, bup_as_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
met_as_12_df <- summarize_results(met_as_1, met_as_2, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
met_as_23_df <- summarize_results(met_as_2, met_as_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
met_as_13_df <- summarize_results(met_as_1, met_as_3, ci_level = 0.95, ci_type = "simult")$diff_est |>
    filter(time > 0)
```

## Plotting Results

### Unadjusted

```{r}
custom_colors <- c("White" = "#e31a1c", "Black" = "#1f78b4", "Hispanic" = "darkseagreen4")

bup_point <- ggplot(data_bup_long, aes(x = week, y = avg, group = xrace, color = xrace)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Buprenorphine Dose by Race (Unadjusted)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

bup_cont <- ggplot(data_bup_long, aes(x = week, y = avg, color = xrace)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = low, ymax = high, fill = xrace), alpha = 0.3) + 
  labs(title = "Mean Buprenorphine Dose by Race (Unadjusted)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

data_bup_long_1 <- data_bup_long |>
    filter(xrace == "White")
    
data_bup_long_2 <- data_bup_long |>
    filter(xrace == "Black")
    
data_bup_long_3 <- data_bup_long |>
    filter(xrace == "Hispanic")
    
unadjust_bup_12 <- unadjusted_diff(data_bup_long_1, data_bup_long_2, ci_type = "simult")

unadjust_bup_13 <- unadjusted_diff(data_bup_long_1, data_bup_long_3, ci_type = "simult")

unadjust_bup_23 <- unadjusted_diff(data_bup_long_2, data_bup_long_3, ci_type = "simult")

bup_unadj_b <- ggplot(unadjust_bup_12, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. B (Unadjusted)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_unadj_c <- ggplot(unadjust_bup_13, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H (Unadjusted)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_unadj_d <- ggplot(unadjust_bup_23, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H (Unadjusted)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_as_figure <- ggarrange(bup_point, bup_unadj_b, bup_unadj_c, bup_unadj_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, 
                  font.label=list(color="black",size=10, family = "Times New Roman"))
bup_as_figure
```

```{r}
met_point <- ggplot(data_met_long, aes(x = week, y = avg, group = xrace, color = xrace)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Methadone Dose by Race (Unadjusted)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

met_cont <- ggplot(data_met_long, aes(x = week, y = avg, color = xrace)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = low, ymax = high, fill = xrace), alpha = 0.3) + 
  labs(title = "Mean Methadone Dose by Race (Unadjusted)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

data_met_long_1 <- data_met_long |>
    filter(xrace == "White")
    
data_met_long_2 <- data_met_long |>
    filter(xrace == "Black")
    
data_met_long_3 <- data_met_long |>
    filter(xrace == "Hispanic")

unadjust_met_12 <- unadjusted_diff(data_met_long_1, data_met_long_2, ci_type = "simult")

unadjust_met_13 <- unadjusted_diff(data_met_long_1, data_met_long_3, ci_type = "simult")

unadjust_met_23 <- unadjusted_diff(data_met_long_2, data_met_long_3, ci_type = "simult")

met_unadj_b <- ggplot(unadjust_met_12, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. B, Unadjusted",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_unadj_c <- ggplot(unadjust_met_13, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H, Unadjusted",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_unadj_d <- ggplot(unadjust_met_23, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H, Unadjusted",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_unadj_figure <- ggarrange(met_point, met_unadj_b, met_unadj_c, met_unadj_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, 
                  font.label=list(color="black",size=10, family = "Times New Roman"))
met_unadj_figure
```

```{r}
#unadjusted 6 plots

bup_point + bup_unadj_b + bup_unadj_c + met_point + met_unadj_b + met_unadj_c + 
  plot_layout(ncol=3,widths=c(0.5, 0.25, 0.25)) + plot_annotation(tag_levels = 'A') &
    theme(plot.tag = element_text(face = 'bold'))
```

### Adjusted -- Sex + Age

```{r}
custom_colors <- c("White" = "#e31a1c", "Black" = "#1f78b4", "Hispanic" = "darkseagreen4") # color scheme, can adjust

## sex and age

bup_lim_point <- ggplot(bup_results_lim, aes(x = week, y = theta, group = race, color = race)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Buprenorphine Dose by Race (Sex + Age)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

bup_lim_cont <- ggplot(bup_results_lim, aes(x = week, y = theta, color = race)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = race), alpha = 0.3) + 
  labs(title = "Mean Buprenorphine Dose by Race (Sex + Age)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

bup_lim_b <- ggplot(bup_as_12_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. B (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_lim_c <- ggplot(bup_as_13_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_lim_d <- ggplot(bup_as_23_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_as_figure <- ggarrange(bup_lim_point, bup_lim_b, bup_lim_c, bup_lim_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, 
                  font.label=list(color="black",size=10, family = "Times New Roman"))
bup_as_figure
```

```{r}
met_lim_point <- ggplot(met_results_lim, aes(x = week, y = theta, group = race, color = race)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Methadone Dose by Race (Sex + Age)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

met_lim_cont <- ggplot(met_results_lim, aes(x = week, y = theta, color = race)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = race), alpha = 0.3) + 
  labs(title = "Mean Methadone Dose by Race (Sex + Age)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

met_lim_b <- ggplot(met_as_12_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. B (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_lim_c <- ggplot(met_as_13_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_lim_d <- ggplot(met_as_23_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H (Sex + Age)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_as_figure <- ggarrange(met_lim_point, met_lim_b, met_lim_c, met_lim_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, hjust= -1,
                  font.label=list(color="black",size=10, family = "Times New Roman"))
met_as_figure
```

```{r}
#sex + age 6 plots

bup_lim_point + bup_lim_b + bup_lim_c + met_lim_point + met_lim_b + met_lim_c + 
  plot_layout(ncol=3,widths=c(0.5, 0.25, 0.25)) + plot_annotation(tag_levels = 'A') &
    theme(plot.tag = element_text(face = 'bold'))
```

### Adjusted -- Expanded Covariates

```{r}
bup_all_point <- ggplot(bup_results_all, aes(x = week, y = theta, group = race, color = race)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Buprenorphine Dose by Race (Full Covariates)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

bup_all_cont <- ggplot(bup_results_all, aes(x = week, y = theta, color = race)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = race), alpha = 0.3) + 
  labs(title = "Mean Buprenorphine Dose by Race (Full Covariates)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

bup_all_b <- ggplot(bup_all_12_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) +  
  labs(title = "W v. B (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_all_c <- ggplot(bup_all_13_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_all_d <- ggplot(bup_all_23_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

bup_all_figure <- ggarrange(bup_all_point, bup_all_b, bup_all_c, bup_all_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, hjust= -1,
                  font.label=list(color="black",size=10, family = "Times New Roman"))
bup_all_figure
```

```{r}
met_all_point <- ggplot(met_results_all, aes(x = week, y = theta, group = race, color = race)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 0.5)) +
  labs(title = "Mean Methadone Dose by Race (Full Covariates)",
       x = "Week",
       y = "Mean Dose") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "", 
         fill = "")

met_all_cont <- ggplot(met_results_all, aes(x = week, y = theta, color = race)) +
  geom_line() +   # Connect means with lines
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = race), alpha = 0.3) + 
  labs(title = "Mean Methadone Dose by Race (Full Covariates)",
       x = "Week",
       y = "Mean Dose",
       color = "Group") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
      scale_color_manual(values = custom_colors) + 
  scale_fill_manual(values = custom_colors) +  
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          legend.key.size = unit(0.25, 'cm'), 
          legend.box.spacing = unit(-5, "pt"),
          text = element_text(size=7, family = "Times New Roman")) + 
    labs(color = "Race", 
         fill = "Race")

met_all_b <- ggplot(met_all_12_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. B (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_all_c <- ggplot(met_all_13_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "W v. H (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_all_d <- ggplot(met_all_23_df, aes(x = time, y = effect_est)) +
    geom_point() + 
  geom_errorbar(aes(ymin = ci_lwr, ymax = ci_upr), width = 0.2) + 
  labs(title = "B v. H (Full Covariates)",
       x = "Week",
       y = "Mean Dose Difference") +
    scale_x_continuous(breaks = seq(1, 4, by = 1)) +
  theme_minimal() +
    theme(plot.title = element_text(vjust = 0.5),
          text = element_text(size=7, family = "Times New Roman")) +
  geom_hline(yintercept=c(0), linetype="dotted")

met_all_figure <- ggarrange(met_all_point, met_all_b, met_all_c, met_all_d + font("x.text", size = 0.5),
                    ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), vjust= 1.75, hjust= -1,
                  font.label=list(color="black",size=10, family = "Times New Roman"))
met_all_figure
```

```{r}
#expanded covar plots

bup_all_point + bup_all_b + bup_all_c + met_all_point + met_all_b + met_all_c + 
  plot_layout(ncol=3,widths=c(0.5, 0.25, 0.25)) + plot_annotation(tag_levels = 'A') &
    theme(plot.tag = element_text(face = 'bold'))
```

## Methods Plots

```{r}
custom_colors_4 <- c("White" = "#e31a1c", "Black" = "#1f78b4", "Hispanic" = "darkseagreen4", 
                     "Censor" = "darkorchid4") # color scheme, can adjust

data_bup_long_censored <- data_bup_long_ungrouped |>
    select(who, week, xrace, dose_this_week, censor) |>
    filter(week <= 4) |>
    mutate(dose_this_week = ifelse(is.na(dose_this_week), 0, dose_this_week),
           xrace = case_when(xrace == "1" ~ "White",
                             xrace == "2" ~ "Black",
                             xrace == "3" ~ "Hispanic", 
                             TRUE ~ xrace),
           xrace = ifelse(censor == 0, "Censor", xrace),
           xrace = factor(xrace, levels = c("White", "Black", "Hispanic", "Censor"))) |>
    arrange(week, xrace) 

bup_alluvial <- ggplot(data_bup_long_censored,
       aes(x = week, stratum = xrace, alluvium = who,
           fill = xrace, label = xrace)) +
  geom_flow() +
  geom_stratum(alpha = .5) +
  geom_text(stat = "stratum", aes(label = after_stat(count)),
            family = "Times New Roman") +
    scale_fill_manual(values = custom_colors_4) +
    theme_void()  +
  guides(fill = guide_legend(title = "")) + labs(x = "Week") +
    theme(axis.title.x = element_text(),
          axis.text.x = element_text(),
        text = element_text(size=12, family = "Times New Roman"), 
          legend.box.spacing = unit(-10, "pt"))

data_met_long_censored <- data_met_long_ungrouped |>
    select(who, week, xrace, dose_this_week, censor) |>
    filter(week <= 4) |>
    mutate(dose_this_week = ifelse(is.na(dose_this_week), 0, dose_this_week),
           xrace = case_when(xrace == "1" ~ "White",
                             xrace == "2" ~ "Black",
                             xrace == "3" ~ "Hispanic", 
                             TRUE ~ xrace),
           xrace = ifelse(censor == 0, "Censor", xrace),
           xrace = factor(xrace, levels = c("White", "Black", "Hispanic", "Censor"))) |>
    arrange(week, xrace)

met_alluvial <- ggplot(data_met_long_censored,
       aes(x = week, stratum = xrace, alluvium = who,
           fill = xrace, label = xrace)) +
  geom_flow() +
  geom_stratum(alpha = .5) +
  geom_text(stat = "stratum", aes(label = after_stat(count)), 
            family = "Times New Roman") +
    scale_fill_manual(values = custom_colors_4) +
    theme_void()  +
  guides(fill = guide_legend(title = "")) + labs(x = "Week") +
    theme(axis.title.x = element_text(),
          axis.text.x = element_text(),
        text = element_text(size=12, family = "Times New Roman"), 
          legend.box.spacing = unit(-10, "pt"))

bup_alluvial + met_alluvial +
  plot_layout(ncol=2,widths=c(0.5, 0.5),
              guides = 'collect') + plot_annotation(tag_levels = 'A') &
    theme(plot.tag = element_text(face = 'bold'))
```

## Misc. Plots

```{r}
bup_sites <- readRDS(here::here("data/processed/bup_sites.rds"))
met_sites <- readRDS(here::here("data/processed/met_sites.rds"))

bup_site_prop_plot <- ggplot(bup_sites, aes(x = week, y = freq, fill = xrace)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~site, scales = "fixed", ncol = 4) +
  labs(title = "Proportion of Race Groups by Site (Bup)", fill = "Race") +
  scale_fill_brewer(palette = "Set1", labels = c("White", "Black", "Hispanic")) +
  theme_minimal() + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(size = 50)) 

met_site_prop_plot <- ggplot(met_sites, aes(x = week, y = freq, fill = xrace)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~site, scales = "free_x", ncol = 4) +
  labs(title = "Proportion of Race Groups by Site (Met)", fill = "Race") +
  scale_fill_brewer(palette = "Set1", labels = c("White", "Black", "Hispanic")) +
  theme_minimal() + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank())

bup_site_count_plot <- ggplot(bup_sites, aes(x = week, y = count, fill = xrace)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~site, scales = "fixed", ncol = 4) +
  labs(title = "Count of Race Groups by Site (Bup)", fill = "Race") +
  scale_fill_brewer(palette = "Set1", labels = c("White", "Black", "Hispanic")) +
  theme_minimal() + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(size = 50))

met_site_count_plot <- ggplot(met_sites, aes(x = week, y = count, fill = xrace)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~site, scales = "free_x", ncol = 5) +
  labs(title = "Count of Race Groups by Site (Met)", fill = "Race") +
  scale_fill_brewer(palette = "Set1", labels = c("White", "Black", "Hispanic")) + 
  theme_minimal() + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank())

#ggsave("bup_site_prop_plot.png", plot = bup_site_prop_plot, width = 20, height = 30, bg="white", dpi = 320)
#ggsave("met_site_prop_plot.png", plot = met_site_prop_plot, bg="white")
#ggsave("bup_site_count_plot.png", plot = bup_site_count_plot, width = 20, height = 30, bg="white", dpi = 320)
#ggsave("met_site_count_plot.png", plot = met_site_count_plot, bg="white")
```
