---
title: "Dose Descriptive Statistics and Modeling"
format: html
editor: visual
---

```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggalluvial)
library(gtsummary)
library(patchwork)
library(lmtp)

knitr::opts_chunk$set(warning=FALSE, message=FALSE)
knitr::opts_chunk$set(fig.width=18, fig.height=12) 

# scripts to make confidence intervals
#source(here::here("scripts/source/utils_adapted.R"))
source(here::here("scripts/source/unadjusted_ci.R"))
```

## Reading/Storing result_newcensors

### Reading result_newcensors for Marginal CI

```{r}
bup_result_newcensors_lim <- data.frame(week = integer(0), race = numeric(0), project = numeric(0), theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

# Loop through the file paths and read the RDS files into data frames
for (z in 1:3)
{
for (j in 1:3)
{
bup_result_newcensors_all_temp <- data.frame(week = numeric(0), race = numeric(0), project = numeric(0),
                                             theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

bup_result_newcensors_lim_temp <- data.frame(week = numeric(0), race = numeric(0), project = numeric(0),
                                             theta = numeric(0), se = numeric(0), lower = numeric(0), upper = numeric(0))

for (i in 4:4) {

    if (i > 2)
    {
  
  data_bup_lim <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", j, sep = "_", i, sep = "_", z, ".rds")))
  bup_result_newcensors_lim_temp[[i, "week"]] <- i
  bup_result_newcensors_lim_temp[[i, "race"]] <- j
  bup_result_newcensors_lim_temp[[i, "project"]] <- z
  bup_result_newcensors_lim_temp[[i, "theta"]] <- data_bup_lim$theta
  bup_result_newcensors_lim_temp[[i, "se"]] <- data_bup_lim$standard_error
  bup_result_newcensors_lim_temp[[i, "lower"]] <- data_bup_lim$low
  bup_result_newcensors_lim_temp[[i, "upper"]] <- data_bup_lim$high
    }
}

bup_result_newcensors_lim <- bup_result_newcensors_lim |>
    merge(bup_result_newcensors_lim_temp, all = TRUE)

}
}

bup_result_newcensors_lim <- bup_result_newcensors_lim |>
    mutate(race = as.factor(race)) |>
    mutate(race = case_when(race == "1" ~ "White",
                             race == "2" ~ "Black",
                             race == "3" ~ "Hispanic"))
```

### Reading result_newcensors for CI

```{r}
# bup limited 
bup_as_1_27 <- list()
bup_as_2_27 <- list()
bup_as_3_27 <- list()

for (z in 1:1)
{
    for (i in 4:4) {
        
        if(i >= 3){
            # continuous
            
            #bup limited
            bup_as_1_27[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "1", sep = "_", i, 
                                                       sep = "_", z, ".rds")))
            
            bup_as_2_27[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "2", sep = "_", i,
                                                       sep = "_", z, ".rds")))
            
            bup_as_3_27[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "3", sep = "_", i,
                                                       sep = "_", z, ".rds")))
        }
    }
    
    lmtp_contrast_simple <- function(X, Y) {
        res <- lmtp_contrast(X, ref = Y)
        
        return(res)
    }
}

bup_as_12_contrast_27 <- mapply(lmtp_contrast_simple, X = bup_as_2_27, Y = bup_as_1_27)

bup_as_12_df_27 <- as.data.frame(bup_as_12_contrast_27[,1]$val) |>
    mutate(time = 4)

bup_as_13_contrast_27 <- mapply(lmtp_contrast_simple, X = bup_as_3_27, Y = bup_as_1_27)

bup_as_13_df_27 <- as.data.frame(bup_as_13_contrast_27[,1]$val) |>
    mutate(time = 4)

##### CTN 30
# bup limited 
bup_as_1_30 <- list()
bup_as_2_30 <- list()
bup_as_3_30 <- list()

for (z in 2:2)
{
    for (i in 4:4) {
        
        if(i >= 3){
            # continuous
            
            #bup limited
            bup_as_1_30[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "1", sep = "_", i, 
                                                       sep = "_", z, ".rds")))
            
            bup_as_2_30[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "2", sep = "_", i,
                                                       sep = "_", z, ".rds")))
            
            bup_as_3_30[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "3", sep = "_", i,
                                                       sep = "_", z, ".rds")))
        }
    }
    
    lmtp_contrast_simple <- function(X, Y) {
        res <- lmtp_contrast(X, ref = Y)
        
        return(res)
    }
}

bup_as_12_contrast_30 <- mapply(lmtp_contrast_simple, X = bup_as_2_30, Y = bup_as_1_30)

bup_as_12_df_30 <- as.data.frame(bup_as_12_contrast_30[,1]$val) |>
    mutate(time = 4)

bup_as_13_contrast_30 <- mapply(lmtp_contrast_simple, X = bup_as_3_30, Y = bup_as_1_30)

bup_as_13_df_30 <- as.data.frame(bup_as_13_contrast_30[,1]$val) |>
    mutate(time = 4)

#### CTN 51
# bup limited 
bup_as_1_51 <- list()
bup_as_2_51 <- list()
bup_as_3_51 <- list()

for (z in 3:3)
{
    for (i in 4:4) {
        
        if(i >= 3){
            # continuous
            
            #bup limited
            bup_as_1_51[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "1", sep = "_", i, 
                                                          sep = "_", z, ".rds")))
            
            bup_as_2_51[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "2", sep = "_", i,
                                                          sep = "_", z, ".rds")))
            
            bup_as_3_51[[1]] <- readRDS(here::here(paste0("./data/trial_stratify/bup/","result_newcensor_limited", "3", sep = "_", i,
                                                          sep = "_", z, ".rds")))
        }
    }
    
    lmtp_contrast_simple <- function(X, Y) {
        res <- lmtp_contrast(X, ref = Y)
        
        return(res)
    }
}

bup_as_12_contrast_51 <- mapply(lmtp_contrast_simple, X = bup_as_2_51, Y = bup_as_1_51)

bup_as_12_df_51 <- as.data.frame(bup_as_12_contrast_51[,1]$val) |>
    mutate(time = 4)

bup_as_13_contrast_51 <- mapply(lmtp_contrast_simple, X = bup_as_3_51, Y = bup_as_1_51)

bup_as_13_df_51 <- as.data.frame(bup_as_13_contrast_51[,1]$val) |>
    mutate(time = 4)


### COMBINING
bup_as_12_df <- bup_as_12_df_27 |>
    mutate(project = "27") |>
    merge(bup_as_12_df_30 |>
    mutate(project = "30"), all = TRUE) |>
    merge(bup_as_12_df_51 |>
    mutate(project = "51"), all = TRUE)

bup_as_13_df <- bup_as_13_df_27 |>
    mutate(project = "27")|>
    merge(bup_as_13_df_30 |>
    mutate(project = "30"), all = TRUE) |>
    merge(bup_as_13_df_51 |>
    mutate(project = "51"), all = TRUE)
```

## Final Plot

```{r}
custom_colors <- c("White" = "#e31a1c", "Black" = "#1f78b4", "Hispanic" = "darkseagreen4")

theta_df <- bup_result_newcensors_lim |>
    filter(is.na(week) == FALSE) |>
    mutate(project = case_when(project == 1 ~ "27",
                               project == 2 ~ "30",
                               project == 3 ~ "51")) |>
    mutate(project = factor(project, levels = c("27", "30", "51")))


diff_df <- bup_as_12_df |> mutate(race = "Black v. White") |>
    merge(bup_as_13_df |> mutate(race = "Hispanic v. White"), all = TRUE)

all_theta_plot <- ggplot(theta_df, aes(x = project, y = theta, group = race, color = race, fill = race, shape = race)) +
    geom_point(position = position_dodge(width = 0.5)) +
    geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 0.5)) +
    labs(title = "",
         x = "trial",
         y = "Dose (mg)") +
    #scale_x_continuous(breaks = seq(1, 4, by = 1)) +
    scale_color_manual(values = custom_colors) + 
    scale_shape_manual(values = c(1, 0, 8)) +
    scale_fill_manual(values = custom_colors) +  
    theme_minimal() +
    labs(color = "",
         shape = "",
         fill = "") +
    #facet_wrap(~trt, scales = "free") + 
    theme(strip.text = element_text(size = 24),
        legend.position = "none",
        plot.title = element_text(vjust = 0.5),
        text = element_text(size = 16, family = "Times New Roman")
    ) 

all_diff_plot <- ggplot(diff_df, aes(x = project, y = theta, group = race, color = race, fill = race, shape = race)) +
    geom_point(position = position_dodge(width = 0.5)) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.25, position = position_dodge(width = 0.5)) +
    labs(title = "",
         x = "Trial",
         y = "Difference in Dose (mg)") +
    geom_hline(yintercept = 0, linetype = "dotted", color = "black") +
    #scale_x_continuous(breaks = seq(1, 4, by = 1)) +
    scale_color_manual(values = c("#1f78b4", "darkseagreen4")) + 
    scale_shape_manual(values = c(1, 0, 8)) +
    scale_fill_manual(values = c("#1f78b4", "darkseagreen4")) +  
    theme_minimal() +
    labs(color = "",
         shape = "",
         fill = "") +
    #facet_wrap(~trt, scales = "free") + 
    theme(strip.text = element_text(size = 24),
        legend.position = "none",
        plot.title = element_text(vjust = 0.5),
        text = element_text(size = 16, family = "Times New Roman")
    ) 

final_plot_cont <- all_theta_plot + all_diff_plot + 
    plot_annotation(tag_levels = 'A') + plot_layout(ncol = 1) & 
    theme(plot.tag = element_text(size = 14),
          panel.border = element_rect(colour = "black", fill=NA))

ggsave(filename = here::here("figures/trial_stratify_as.png"),
       plot = final_plot_cont,
       width = 15, height = 20)
```

```{r}
data_bup <- readRDS(here::here("data/processed/data_bup_imputed.rds")) 

dat <- data_bup |>
  filter(project == "30") |>
  mutate(xrace2 = case_when(xrace == "1" ~ "NHW",
                            xrace == "2" ~ "NHB",
                            xrace == "3" ~ "Hispanic")) |>
  mutate(xrace2 = factor(xrace2, levels = c("NHW", "NHB", "Hispanic"))) |>
  pivot_longer(
    cols = starts_with("wk"),
    names_to = c("week", ".value"),
    names_pattern = "wk(\\d+)\\.(.*)"
  ) |>
  filter(week <= 4,
         censor == 1)

ggplot(dat, aes(x = dose_this_week, fill = xrace2)) +
  geom_boxplot(position = "dodge", alpha = 0.7) +
  facet_grid(week~xrace2, scales = "free_y", switch = "y") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1") +  # Change the color palette
  labs(title ="Boxplot of Bup Doses Stratified by Race (CTN30)",
       x = "Bup Dose (mg)",
       y = "Week",
       fill = "Race") + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.placement = "outside",
        plot.title = element_text(hjust = 0.5))
```

